apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app-pipeline
  template:
    metadata:
      labels:
        app: register-app-pipeline
    spec:
      containers:
        - name: register-app-pipeline:1.0.0-26
          image: tranvix0910/register-app-pipeline:1.0.0-26
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
